# Generated by Django 4.2.26 on 2025-11-09 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance & Repairs'), ('utilities', 'Utilities'), ('insurance', 'Insurance'), ('property_tax', 'Property Tax'), ('management_fee', 'Management Fee'), ('mortgage', 'Mortgage Payment'), ('hoa', 'HOA Fees'), ('marketing', 'Marketing'), ('legal', 'Legal Fees'), ('supplies', 'Supplies'), ('other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('financial_property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.property')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('rent', 'Rent'), ('late_fee', 'Late Fee'), ('security_deposit', 'Security Deposit'), ('parking', 'Parking'), ('maintenance', 'Maintenance Fee'), ('other', 'Other')], default='rent', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues_created', to=settings.AUTH_USER_MODEL)),
                ('financial_property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='properties.property')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='leases.lease')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Revenue',
                'verbose_name_plural': 'Revenues',
                'db_table': 'revenues',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('late', 'Late'), ('partial', 'Partially Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('late_fee_applied', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.property')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='leases.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financials.expense')),
                ('financial_property', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='properties.property')),
                ('revenue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financials.revenue')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['financial_property', 'date'], name='transaction_propert_0919f5_idx'), models.Index(fields=['transaction_type'], name='transaction_transac_ddda52_idx'), models.Index(fields=['status'], name='transaction_status_505a2f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['financial_property', 'date'], name='revenues_propert_6f22f9_idx'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['tenant', 'date'], name='revenues_tenant__4ea3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['source'], name='revenues_source_9cd468_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['lease', 'due_date'], name='payments_lease_i_2b80ed_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'status'], name='payments_tenant__c38e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['financial_property', 'due_date'], name='payments_propert_2a59f9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['financial_property', 'date'], name='expenses_propert_ee561f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='expenses_categor_a6f264_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid'], name='expenses_paid_b2bfba_idx'),
        ),
    ]
