# Generated by Django 4.2.7 on 2025-11-19 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_date_of_birth_user_email_notifications_and_more"),
        ("users", "0002_user_is_superadmin"),
    ]

    operations = []
