# Generated by Django 4.2.26 on 2025-11-09 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('lease_expiring', 'Lease Expiring'), ('lease_expired', 'Lease Expired'), ('payment_due', 'Payment Due'), ('payment_overdue', 'Payment Overdue'), ('payment_received', 'Payment Received'), ('maintenance_created', 'Maintenance Request Created'), ('maintenance_updated', 'Maintenance Request Updated'), ('maintenance_completed', 'Maintenance Request Completed'), ('document_uploaded', 'Document Uploaded'), ('report_ready', 'Report Ready'), ('tenant_added', 'Tenant Added'), ('tenant_updated', 'Tenant Updated')], max_length=50)),
                ('title_template', models.CharField(help_text='Use {variable} for dynamic content', max_length=255)),
                ('message_template', models.TextField(help_text='Use {variable} for dynamic content')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_lease_expiring', models.BooleanField(default=True)),
                ('email_payment_due', models.BooleanField(default=True)),
                ('email_payment_received', models.BooleanField(default=True)),
                ('email_maintenance_updates', models.BooleanField(default=True)),
                ('email_document_uploaded', models.BooleanField(default=False)),
                ('email_report_ready', models.BooleanField(default=True)),
                ('app_lease_expiring', models.BooleanField(default=True)),
                ('app_payment_due', models.BooleanField(default=True)),
                ('app_payment_received', models.BooleanField(default=True)),
                ('app_maintenance_updates', models.BooleanField(default=True)),
                ('app_document_uploaded', models.BooleanField(default=True)),
                ('app_report_ready', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=20)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('lease_expiring', 'Lease Expiring'), ('lease_expired', 'Lease Expired'), ('payment_due', 'Payment Due'), ('payment_overdue', 'Payment Overdue'), ('payment_received', 'Payment Received'), ('maintenance_created', 'Maintenance Request Created'), ('maintenance_updated', 'Maintenance Request Updated'), ('maintenance_completed', 'Maintenance Request Completed'), ('document_uploaded', 'Document Uploaded'), ('report_ready', 'Report Ready'), ('tenant_added', 'Tenant Added'), ('tenant_updated', 'Tenant Updated')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='e.g., property, lease, payment', max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate when clicked', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notification expiry time', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
