# Generated by Django 4.2.26 on 2025-11-09 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for the API key', max_length=255)),
                ('key_prefix', models.CharField(help_text='First 8 characters of the key', max_length=8, unique=True)),
                ('key_hash', models.CharField(help_text='SHA256 hash of the full key', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_ips', models.TextField(blank=True, help_text='Comma-separated list of allowed IP addresses')),
                ('rate_limit', models.IntegerField(default=1000, help_text='Requests per hour')),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField(help_text='Response time in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api_keys.apikey')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['api_key', 'timestamp'], name='api_keys_ap_api_key_61c98b_idx'), models.Index(fields=['timestamp'], name='api_keys_ap_timesta_337266_idx'), models.Index(fields=['status_code'], name='api_keys_ap_status__f26dbd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user', 'is_active'], name='api_keys_ap_user_id_07b261_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_prefix'], name='api_keys_ap_key_pre_4994e1_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['is_active'], name='api_keys_ap_is_acti_1dc9d8_idx'),
        ),
    ]
